### ISSUE TITLE
id, class, style etc.

### ISSUE THREAD

**Issue by Gunnar-GO** [Gittenburg/WhitelistHTMLTags#1]
Hi,

ich teste gerade einige Erweiterungen und bin auf diese gestoßen. Diese Erweiterung ist für mich sehr interessant (insbesondere wegen aufklappbaren Elementen wie details und summary), allerdings würde ich gerne auch alternativen nutzen, wie diese [1]. Über Target, show und hide. Ich würde diese gerne verwenden.

Leider werden alle Eintragungen außer dem tag an sich bereinigt, so dass die Adressierung nicht möglich ist. Die Attribute werden scheint es nicht übergeben.

Beste Grüße
Gunnar

[1] https://stackoverflow.com/questions/15095933/pure-css-collapse-expand-div

**Comment by Gittenburg** [comment]
Hi, sorry für die späte Antwort (hab vergessen Benachrichtigungen für die Repo anzuschalten).

Gute Idee, sollte mit dem neusten Commit funktionieren.
